spring.application.name=claimguard-backend
server.port=8080

# Activates application-local.properties automatically
spring.profiles.active=local

# JPA / Hibernate (safe to keep here - no secrets)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true